/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package speechrecognz;

public class App {
    

    public static void main(String[] args) throws Exception {
        SpeechToText.streamingMicRecognize();
    }
}
